# BuckDuit Flask + React — Render Config (Final Version)

services:
  - type: web
    name: buckduit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: buckduit-frontend
    env: node
    buildCommand: cd buckduit-frontend && npm install && npm run build
    staticPublishPath: buckduit-frontend/build
    plan: free
    autoDeploy: true
