services:
  - type: web
    name: buckduit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true

  - type: static
    name: buckduit-frontend
    env: static
    buildCommand: cd buckduit-frontend && npm install && npm run build
    staticPublishPath: buckduit-frontend/build
    plan: free
    autoDeploy: true
