services:
  - type: web
    name: buckduit-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: true

  - type: web
    name: buckduit-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: build
    plan: free
    autoDeploy: true
