services:
  - type: web
    name: buckduit-backend
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app --bind 0.0.0.0:10000 --workers 2"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: buckduit-db
          property: connectionString
    autoDeploy: true

databases:
  - name: buckduit-db
    plan: free
    region: singapore
